version: "3.3"
services:
  db:
    image: mysql
    container_name: mysql_tkt
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_tkt
    restart: always
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      PMA_HOST: db


  www:
    build: php
    container_name: www_tkt
    ports:
      - 8742:80
    volumes:
      - ./php/vhosts:/etc/apache2//sites-enabled
      - ./:/var/www
